version: '3'

services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    ports:
      - "4317:4317"
    volumes:
      - ./otel-collector-config.yml:/otel-local-config.yaml
    command: ["--config", "/otel-local-config.yaml"]
